### PR TITLE
S3 download class implementation

### PR DESCRIPTION
**Pull request by apozsuse**
This PR includes the implementation for the `S3DownloadJob` class.

### File naming scheme

The naming scheme agreed for the image files in the bucket is the following:

```
AWS:
    suse-liberty-$MAJOR-$MINOR-byos-vYYYYMMDD-$ARCH.raw.xz

Azure
    liberty-$MAJOR-$MINOR-byos-vYYYYMMDD-$ARCH.vhdfixed.xz

Google
    liberty-$MAJOR-$MINOR-byos-vYYYYMMDD-$ARCH.tar.gz
```

A couple new fields in the `mash` job document schema are included in this PR to keep mash abstracted from these details:

- `s3_download_file_prefix`: A prefix to be prepended to the image_name for the file download. The expected value for this is `suse-` for AWS and empty string (or not include the field) for the rest of cloud providers.
- `s3_download_file_suffix`: Same but for the suffix to be appended after the `$ARCH` segment.

For the bucket address the `download_url` file is reused.

### Authentication

A new field has been included(`download_account`) in the `mash` job document to include the account that will be used to authenticate in aws to access the S3 bucket.
The credentials corresponding to that account have to be provisioned in mash as usual.

### CODE REVIEW

**Review by smarlowucf — COMMENTED** [review]
If there was an overlap with extensions between two clouds and images were uploaded on the same day the files would stomp on each other. Should we request that files are uploaded using csp names that are included in the filename like:

```
google/liberty-$MAJOR-$MINOR-byos-vYYYYMMDD-$ARCH.tar.gz
microsoft/liberty-$MAJOR-$MINOR-byos-vYYYYMMDD-$ARCH.vhdfixed.xz
amazon/suse-liberty-$MAJOR-$MINOR-byos-vYYYYMMDD-$ARCH.raw.xz
```

Where the prefix could be the "cspname/..." part.

**Comment by rjschwei** [comment]
> If there was an overlap with extensions between two clouds and images were uploaded on the same day the files would stomp on each other. Should we request that files are uploaded using csp names that are included in the filename like:
> 
> ```
> google/liberty-$MAJOR-$MINOR-byos-vYYYYMMDD-$ARCH.tar.gz
> microsoft/liberty-$MAJOR-$MINOR-byos-vYYYYMMDD-$ARCH.vhdfixed.xz
> amazon/suse-liberty-$MAJOR-$MINOR-byos-vYYYYMMDD-$ARCH.raw.xz
> ```
> 
> Where the prefix could be the "cspname/..." part. Maybe this isn't an issue now but something to consider for the future. I believe OCI uses qcow2 files so there's no current overlap.

There should never be an overlap

> If there was an overlap with extensions between two clouds and images were uploaded on the same day the files would stomp on each other. Should we request that files are uploaded using csp names that are included in the filename like:
> 
> ```
> google/liberty-$MAJOR-$MINOR-byos-vYYYYMMDD-$ARCH.tar.gz
> microsoft/liberty-$MAJOR-$MINOR-byos-vYYYYMMDD-$ARCH.vhdfixed.xz
> amazon/suse-liberty-$MAJOR-$MINOR-byos-vYYYYMMDD-$ARCH.raw.xz
> ```
> 
> Where the prefix could be the "cspname/..." part. Maybe this isn't an issue now but something to consider for the future. I believe OCI uses qcow2 files so there's no current overlap.

Well the only possible overlap would be if some other cloud framework implementation expected a tarball that is gzip compressed and the format of the data in the image would be different than what we expect for GCE. That said the separation into subdirectories in general, as suggested, to avoid potential collisions is already supported via the `download_url` setting in the jobdoc .

**Comment by rjschwei** [comment]
I am not convinced that we need `s3_download_file_suffix` and `s3_download_file_prefix`.

For our use case where we want to support image uploads for images build outside the Open Build Service and pull those images from an S3 bucket we simply prescribe that the name prior to the first `.` must match our image names as they appear in the frameworks where we publish images. For all other users the construction of the filename via `s3_download_file_suffix` and `s3_download_file_prefix` is probably  cumbersome.

Secondly `mash` makes assumptions about how the image file format relates to a specific framework, for example one cannot create an image in EC2 with mash if the origin build is in qcow2 format. Therefore I think sticking to the approach taken in obs-img-utils [1] is the way to go here as well. Loop over the defined extensions and prepend each with the known `image-name` and that's what we download.

[1] https://github.com/SUSE-Enceladus/obs-img-utils/blob/main/obs_img_utils/utils.py#L36

**Comment by apozsuse** [comment]
> Secondly `mash` makes assumptions about how the image file format relates to a specific framework, for example one cannot create an image in EC2 with mash if the origin build is in qcow2 format. Therefore I think sticking to the approach taken in obs-img-utils [1] is the way to go here as well. Loop over the defined extensions and prepend each with the known `image-name` and that's what we download.
> 
> [1] https://github.com/SUSE-Enceladus/obs-img-utils/blob/main/obs_img_utils/utils.py#L36

The `obs-img-utils` approach works in OBS because we've got the `profile` field that makes the image name (without the extension) `unique` per cloud (the name is unique, so we just loop around the possible extensions until we find one matching).

In this case, as the name can be equal for 2 different clouds (if we need to publish amazon and google the same day for example), we need to include the logics to get the exact file name (with the extension) depending on the cloud naming schema somewhere.

May be having a single `download_file_name` field in the mash job doc would be easier than having a prefix and suffix?

**Comment by smarlowucf** [comment]
Agree on the prefix. The "suse-" part for ec2 images is treated as part of the image name everywhere else. So an extra suffix arg isn't really needed.

Based on the example filenames provided here they don't compare to what obs-img-utils is working with though. In that case the format is like `SLES15-SP5-BYOS.aarch64-1.0.3-GCE-Build1.9.tar.gz`. There is a token in there to distinguish cloud framework. Unless there's a token in the filenames in s3 with this data how will we know where the image should go?

**Comment by rjschwei** [comment]
> Agree on the prefix. The "suse-" part for ec2 images is treated as part of the image name everywhere else. So an extra suffix arg isn't really needed.
> 
> Based on the example filenames provided here they don't compare to what obs-img-utils is working with though. In that case the format is like `SLES15-SP5-BYOS.aarch64-1.0.3-GCE-Build1.9.tar.gz`. There is a token in there to distinguish cloud framework. Unless there's a token in the filenames in s3 with this data how will we know where the image should go?

Well, we should not build the answer  of "where the image should go" based on the extension of the file name or a "token" in the filename and we have not done that. Nor should we build around whether or not there is only 1 file downloaded (more on the one file downloaded in the answer to @apozsuse in a minute). The jobdoc has the `provider` key and that answers where the image should go. So in general the schematics in obs-img-utils will still work.

**Comment by rjschwei** [comment]
> > Secondly `mash` makes assumptions about how the image file format relates to a specific framework, for example one cannot create an image in EC2 with mash if the origin build is in qcow2 format. Therefore I think sticking to the approach taken in obs-img-utils [1] is the way to go here as well. Loop over the defined extensions and prepend each with the known `image-name` and that's what we download.
> > [1] https://github.com/SUSE-Enceladus/obs-img-utils/blob/main/obs_img_utils/utils.py#L36
> 
> The `obs-img-utils` approach works in OBS because we've got the `profile` field that makes the image name (without the extension) `unique` per cloud (the name is unique, so we just loop around the possible extensions until we find one matching).
> 
> In this case, as the name can be equal for 2 different clouds (if we need to publish amazon and google the same day for example), we need to include the logics to get the exact file name (with the extension) depending on the cloud naming schema somewhere.
> 
> May be having a single `download_file_name` field in the mash job doc would be easier than having a prefix and suffix?

Having a `download_file_name`  works for me. That said it is not strictly necessary. In the example provided where image files for different clouds are the same but for the extension we would simply download 2 files if we were to loop over the expected extensions. The mash uploader, for example [1] then finds the proper file for the cloud target specified with the `provider` key in the jobdoc.

That said in order to be resource consumption friendly on only download what we need at the time we need it having  a `download_file_name` key is the responsible approach.


[1] https://github.com/SUSE-Enceladus/mash/blob/main/mash/services/upload/gce_job.py#L87

**Comment by smarlowucf** [comment]
Isn't the file showing up in the s3 bucket that triggers this process though? If that's the initial trigger then it needs to communicate all the necessary info in some way; filename, cloud, image name. There's many ways we can go about that. But if we have one bucket then one example could be filename of: `google/liberty-15-6-byos-v20240101-x86_64.tar.gz`. E.g. `{cloud}/{image name}.{ext}`. Another option is one bucket per cloud and filename then could be `{image name}.{ext}`. Either way the monitor script would parse this and could prevent any SUSE specific logic getting into mash.

**Comment by rjschwei** [comment]
> Isn't the file showing up in the s3 bucket what triggers this process though? If that's the initial trigger then it needs to communicate all the necessary info in some way; filename, cloud, image name. There's many ways we can go about that. But if we have one bucket then one example could be filename of: `google/liberty-15-6-byos-v20240101-x86_64.tar.gz`. E.g. `{cloud}/{image name}.{ext}`. Another option is one bucket per cloud and filename then could be `{image name}.{ext}`. Either way the monitor script would parse this and could prevent any SUSE specific logic getting into mash.

This gets into a conversation that is outside the scope of this PR and some parts of that conversation should not be public.

**Comment by apozsuse** [comment]
Closing this PR to create new ones with the agreed approach to this feature.

**Pull request closed without merging**
