### PR TITLE
Add next service attribute to services.

### PR DESCRIPTION
**Pull request by smarlowucf**
This removes hard coded service names from classes and is a step to share messaging code.

### CODE REVIEW

**Comment by rjschwei** [comment]
Since you are going through the trouble to refactor this why not get to the end result in one step as it requires probably an equal amount of work.

We have the service order in config/mash_config.yaml so instead of hardcoding into "uploader" that the next service is "testing" each service should call _set_next_service in the c-tor and _set_next_service is implemented in the base class and reads the config and based on self.service_name finds the next service from the config and sets self.next_service

Sorry I a missing where the hardcoding approach in this patch set makes the changeset smaller compared to the more general approach.

**Comment by smarlowucf** [comment]
End goal to change:

`publish_stuff(stuff, 'deprecation')`

to

`publish_stuff(stuff, self.last_service)`

because the latter can move to base service.

**Comment by smarlowucf** [comment]
Updated to use service list.

**Comment by smarlowucf** [comment]
Rebased to fix merge conflicts.

**Pull request merged**
